ALTER VIEW [dbo].[v_Clearing]
AS
SELECT 
    TrxRowID,
    Trxbatchid,
    TrxbatchSlNo,
    OurBranchID,
    AccountTypeID,
    AccountID,
    ChequeDigit,
    VoucherCode,
    ReturnCodeID,
    Commission,
    TheirCommission,
    PinNumber,
    PaymentType,
    PaymentTypeID,
    PaymentDate,
    VATName,
    VATNumber,
    VATType,
    VATSerialNo,
    BankID,
    BranchID,
    DrawerOrPayeeAccountID,
    DrawerOrPayee,
    Amount,
    ChequeID,
    ChequeDate,
    Valuedate,
    CurrencyID,
    Date as TrxDate,
    OriginatorCode,
    OrigRefCode,
    PolicyNumber1,
    PolicyNumber2,
    TrxBranchID,
    Trxtype as TrxTypeID,
    ImageID,
    IsUnpaidItem,
    SessNo,
    IsDeleted,
    ColumnID,
    -- Columns that exist in t_AccountTrxClearing
    IsGenerated,
    -- Columns that don't exist in t_AccountTrxClearing - use NULL or empty string
    CAST(NULL AS VARCHAR(50)) as TrxStatus,
    CAST(NULL AS VARCHAR(255)) as Remarks,
    DRN,
    Reference
FROM t_AccountTrxClearing WITH (NOLOCK)

UNION ALL

SELECT 
    TrxRowID,
    Trxbatchid,
    TrxbatchSlNo,
    OurBranchID,
    AccountTypeID,
    AccountID,
    ChequeDigit,
    VoucherCode,
    ReturnCodeID,
    Commission,
    TheirCommission,
    PinNumber,
    PaymentType,
    PaymentTypeID,
    PaymentDate,
    VATName,
    VATNumber,
    VATType,
    VATSerialNo,
    BankID,
    BranchID,
    DrawerOrPayeeAccountID,
    DrawerOrPayee,
    Amount,
    ChequeID,
    ChequeDate,
    Valuedate,
    CurrencyID,
    Date as TrxDate,
    OriginatorCode,
    OrigRefCode,
    PolicyNumber1,
    PolicyNumber2,
    TrxBranchID,
    Trxtype as TrxTypeID,
    ImageID,
    IsUnpaidItem,
    SessNo,
    IsDeleted,
    ColumnID,
    -- All these columns exist in t_trxclearing
    IsGenerated,
    TrxStatus,
    Remarks,
    DRN,
    Reference
FROM t_trxclearing WITH (NOLOCK)