'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace WebService
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="IEServiceSoap", [Namespace]:="http://www.craftsilicon.com/banking/core")>  _
    Partial Public Class IEService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private GetConnectionStringOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetConnectionStringServiceOperationCompleted As System.Threading.SendOrPostCallback
        
        Private AuthenticateUserFromServiceOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.BrClearing.Common.My.MySettings.Default.BrClearing_WebService_IEService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event GetConnectionStringCompleted As GetConnectionStringCompletedEventHandler
        
        '''<remarks/>
        Public Event GetConnectionStringServiceCompleted As GetConnectionStringServiceCompletedEventHandler
        
        '''<remarks/>
        Public Event AuthenticateUserFromServiceCompleted As AuthenticateUserFromServiceCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.craftsilicon.com/banking/core/GetConnectionString", RequestNamespace:="http://www.craftsilicon.com/banking/core", ResponseNamespace:="http://www.craftsilicon.com/banking/core", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetConnectionString() As String
            Dim results() As Object = Me.Invoke("GetConnectionString", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetConnectionStringAsync()
            Me.GetConnectionStringAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetConnectionStringAsync(ByVal userState As Object)
            If (Me.GetConnectionStringOperationCompleted Is Nothing) Then
                Me.GetConnectionStringOperationCompleted = AddressOf Me.OnGetConnectionStringOperationCompleted
            End If
            Me.InvokeAsync("GetConnectionString", New Object(-1) {}, Me.GetConnectionStringOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetConnectionStringOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetConnectionStringCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetConnectionStringCompleted(Me, New GetConnectionStringCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.craftsilicon.com/banking/core/GetConnectionStringService", RequestNamespace:="http://www.craftsilicon.com/banking/core", ResponseNamespace:="http://www.craftsilicon.com/banking/core", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetConnectionStringService(ByVal strDataBase As String) As String
            Dim results() As Object = Me.Invoke("GetConnectionStringService", New Object() {strDataBase})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetConnectionStringServiceAsync(ByVal strDataBase As String)
            Me.GetConnectionStringServiceAsync(strDataBase, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetConnectionStringServiceAsync(ByVal strDataBase As String, ByVal userState As Object)
            If (Me.GetConnectionStringServiceOperationCompleted Is Nothing) Then
                Me.GetConnectionStringServiceOperationCompleted = AddressOf Me.OnGetConnectionStringServiceOperationCompleted
            End If
            Me.InvokeAsync("GetConnectionStringService", New Object() {strDataBase}, Me.GetConnectionStringServiceOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetConnectionStringServiceOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetConnectionStringServiceCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetConnectionStringServiceCompleted(Me, New GetConnectionStringServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.craftsilicon.com/banking/core/AuthenticateUserFromService", RequestNamespace:="http://www.craftsilicon.com/banking/core", ResponseNamespace:="http://www.craftsilicon.com/banking/core", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function AuthenticateUserFromService(ByVal UInfoXML As String) As String
            Dim results() As Object = Me.Invoke("AuthenticateUserFromService", New Object() {UInfoXML})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub AuthenticateUserFromServiceAsync(ByVal UInfoXML As String)
            Me.AuthenticateUserFromServiceAsync(UInfoXML, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub AuthenticateUserFromServiceAsync(ByVal UInfoXML As String, ByVal userState As Object)
            If (Me.AuthenticateUserFromServiceOperationCompleted Is Nothing) Then
                Me.AuthenticateUserFromServiceOperationCompleted = AddressOf Me.OnAuthenticateUserFromServiceOperationCompleted
            End If
            Me.InvokeAsync("AuthenticateUserFromService", New Object() {UInfoXML}, Me.AuthenticateUserFromServiceOperationCompleted, userState)
        End Sub
        
        Private Sub OnAuthenticateUserFromServiceOperationCompleted(ByVal arg As Object)
            If (Not (Me.AuthenticateUserFromServiceCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent AuthenticateUserFromServiceCompleted(Me, New AuthenticateUserFromServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub GetConnectionStringCompletedEventHandler(ByVal sender As Object, ByVal e As GetConnectionStringCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetConnectionStringCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub GetConnectionStringServiceCompletedEventHandler(ByVal sender As Object, ByVal e As GetConnectionStringServiceCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetConnectionStringServiceCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub AuthenticateUserFromServiceCompletedEventHandler(ByVal sender As Object, ByVal e As AuthenticateUserFromServiceCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class AuthenticateUserFromServiceCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
