CREATE     VIEW [dbo].[v_Clearing]
 
AS
	SELECT	TrxRowID,
            Trxbatchid,
			TrxbatchSlNo,
			OurBranchID,
			AccountTypeID,
			AccountID,
			ChequeDigit,
			VoucherCode,
			ReturnCodeID,
			Commission,
			TheirCommission,
			PinNumber,
			PaymentType,
			PaymentTypeID,
			PaymentDate,
			VATName,
			VATNumber,
			VATType,
		    VATSerialNo,
			BankID,
			BranchID,
			--DrawerOrPayeeAccountID,
			LTRIM(RTRIM(DrawerOrPayeeAccountID)) AS DrawerOrPayeeAccountID, --bnyaswa
			DrawerOrPayee,
			Amount,
			ChequeID,
			ChequeDate,
			Valuedate,
			CurrencyID,
			Date TrxDate,
			OriginatorCode,
			OrigRefCode,
			PolicyNumber1,
			PolicyNumber2,
			TrxBranchID,
			Trxtype TrxTypeID,
			ImageID,
			IsUnpaidItem,
			IsGenerated,
			TrxStatus,
			IsDeleted,
			Remarks,
			Reference,
			ColumnID,
			DRN,
			TrxType,
			DATE
	FROM	t_AccountTrxClearing(NOLOCK)
	UNION 
	SELECT	TrxRowID,
			Trxbatchid,
			TrxbatchSlNo,
			OurBranchID,
			-- For OD (outward EFT) rows: use originator customer account stored in Reference.
			-- Reference was populated by p_PostUploadFileData after p_AddOutwardTrx runs.
			-- For all other TrxTypes, or if Reference is NULL, fall back to the original GL AccountID.
			CASE
				WHEN Trxtype = 'OD' AND ISNULL(Reference, '') <> ''
					THEN AccountTypeID   -- already updated to 'C' by p_PostUploadFileData UPDATE
				ELSE AccountTypeID
			END AS AccountTypeID,
			CASE
				WHEN Trxtype = 'OD' AND ISNULL(Reference, '') <> ''
					THEN Reference       -- originator customer account (e.g. company salary payer)
				ELSE AccountID           -- GL account (CEN_BANK_AC) for all other cases
			END AS AccountID,
			ChequeDigit,
			VoucherCode,
			ReturnCodeID,
			Commission,
			TheirCommission,
			PinNumber,
			PaymentType,
			PaymentTypeID,
			PaymentDate,
			VATName,
			VATNumber,
			VATType,
			VATSerialNo,
			BankID,
			BranchID,
			--DrawerOrPayeeAccountID,
			LTRIM(RTRIM(DrawerOrPayeeAccountID)) AS DrawerOrPayeeAccountID, --bnyaswa
			DrawerOrPayee,
			Amount,
			ChequeID,
			ChequeDate,
			Valuedate,
			CurrencyID,
			Date TrxDate,
			OriginatorCode,
			OrigRefCode,
			PolicyNumber1,
			PolicyNumber2,
			TrxBranchID,
			Trxtype TrxtypeID,
			ImageID,
			IsUnpaidItem,
			IsGenerated,
			TrxStatus,
			IsDeleted,
			Remarks,
			Reference,
			ColumnID,
			DRN,
			TrxType,
			DATE
	FROM	t_trxclearing(NOLOCK)
