ColumnID	bigint	no	8	19   	0    	no	(n/a)	(n/a)	NULL
OurBankID	BankID	no	12	     	     	yes	(n/a)	(n/a)	SQL_Latin1_General_CP1_CI_AS
Date	smalldatetime	no	4	     	     	yes	(n/a)	(n/a)	NULL
FileName	Names	no	200	     	     	yes	(n/a)	(n/a)	SQL_Latin1_General_CP1_CI_AS
Data	Description	no	510	     	     	yes	(n/a)	(n/a)	SQL_Latin1_General_CP1_CI_AS
OurBranchID	BranchID	no	12	     	     	yes	(n/a)	(n/a)	SQL_Latin1_General_CP1_CI_AS
AccountType	varchar	no	2	     	     	yes	no	yes	SQL_Latin1_General_CP1_CI_AS
AccountID	AccountID	no	40	     	     	yes	(n/a)	(n/a)	SQL_Latin1_General_CP1_CI_AS
TrxType	varchar	no	2	     	     	yes	no	yes	SQL_Latin1_General_CP1_CI_AS
ChequeID	int	no	4	10   	0    	yes	(n/a)	(n/a)	NULL
Amount	Amount	no	8	19   	4    	yes	(n/a)	(n/a)	NULL
BankID	BankID	no	12	     	     	yes	(n/a)	(n/a)	SQL_Latin1_General_CP1_CI_AS
BranchID	BranchID	no	12	     	     	yes	(n/a)	(n/a)	SQL_Latin1_General_CP1_CI_AS
TheirAccount	AccountID	no	40	     	     	yes	(n/a)	(n/a)	SQL_Latin1_General_CP1_CI_AS
Description	Description	no	510	     	     	yes	(n/a)	(n/a)	SQL_Latin1_General_CP1_CI_AS
TrxDescriptionID	varchar	no	6	     	     	yes	no	yes	SQL_Latin1_General_CP1_CI_AS
ExtraDetails	Description	no	510	     	     	yes	(n/a)	(n/a)	SQL_Latin1_General_CP1_CI_AS
ChequeDigit	varchar	no	2	     	     	yes	no	yes	SQL_Latin1_General_CP1_CI_AS
VoucherCode	varchar	no	2	     	     	yes	no	yes	SQL_Latin1_General_CP1_CI_AS
ReturnCode	varchar	no	5	     	     	yes	no	yes	SQL_Latin1_General_CP1_CI_AS
DrawerOrPayee	Names	no	200	     	     	yes	(n/a)	(n/a)	SQL_Latin1_General_CP1_CI_AS
DRN	varchar	no	100	     	     	yes	no	yes	SQL_Latin1_General_CP1_CI_AS
MicrLine	varchar	no	100	     	     	yes	no	yes	SQL_Latin1_General_CP1_CI_AS
OriginatorCode	nvarchar	no	100	     	     	yes	(n/a)	(n/a)	SQL_Latin1_General_CP1_CI_AS
OriginatorRef	nvarchar	no	100	     	     	yes	(n/a)	(n/a)	SQL_Latin1_General_CP1_CI_AS
Policy1	nvarchar	no	100	     	     	yes	(n/a)	(n/a)	SQL_Latin1_General_CP1_CI_AS
Policy2	nvarchar	no	100	     	     	yes	(n/a)	(n/a)	SQL_Latin1_General_CP1_CI_AS
Status	varchar	no	10	     	     	yes	no	yes	SQL_Latin1_General_CP1_CI_AS
FullName	varchar	no	250	     	     	yes	no	yes	SQL_Latin1_General_CP1_CI_AS
FRONTGRAYSCALEIMAGE	text	no	16	     	     	yes	(n/a)	(n/a)	SQL_Latin1_General_CP1_CI_AS
FRONTBWIMAGE	text	no	16	     	     	yes	(n/a)	(n/a)	SQL_Latin1_General_CP1_CI_AS
REARIMAGE	text	no	16	     	     	yes	(n/a)	(n/a)	SQL_Latin1_General_CP1_CI_AS
UVIMAGE	text	no	16	     	     	yes	(n/a)	(n/a)	SQL_Latin1_General_CP1_CI_AS
Validity	bit	no	1	     	     	yes	(n/a)	(n/a)	NULL
ProductID	ProductID	no	12	     	     	yes	(n/a)	(n/a)	SQL_Latin1_General_CP1_CI_AS
ModuleID	smallint	no	2	5    	0    	yes	(n/a)	(n/a)	NULL
CurrencyID	CurrencyID	no	6	     	     	yes	(n/a)	(n/a)	SQL_Latin1_General_CP1_CI_AS
InstrumentTypeID	varchar	no	2	     	     	yes	no	yes	SQL_Latin1_General_CP1_CI_AS
MainGLID	AccountID	no	40	     	     	yes	(n/a)	(n/a)	SQL_Latin1_General_CP1_CI_AS
ContraGLID	AccountID	no	40	     	     	yes	(n/a)	(n/a)	SQL_Latin1_General_CP1_CI_AS
ImageID	varchar	no	30	     	     	yes	no	yes	SQL_Latin1_General_CP1_CI_AS
PostedBy	OperatorID	no	50	     	     	yes	(n/a)	(n/a)	SQL_Latin1_General_CP1_CI_AS
TrxBranchID	BranchID	no	12	     	     	no	(n/a)	(n/a)	SQL_Latin1_General_CP1_CI_AS
VoucherCodeDescription	Names	no	200	     	     	yes	(n/a)	(n/a)	SQL_Latin1_General_CP1_CI_AS
IsReconsilable	bit	no	1	     	     	yes	(n/a)	(n/a)	NULL
Reason	Description	no	510	     	     	yes	(n/a)	(n/a)	SQL_Latin1_General_CP1_CI_AS
Paid	bit	no	1	     	     	yes	(n/a)	(n/a)	NULL
Returned	bit	no	1	     	     	yes	(n/a)	(n/a)	NULL
Represented	bit	no	1	     	     	yes	(n/a)	(n/a)	NULL
Escalated	bit	no	1	     	     	yes	(n/a)	(n/a)	NULL
EscalatedOn	datetime	no	8	     	     	yes	(n/a)	(n/a)	NULL
EscalatedBy	OperatorID	no	50	     	     	yes	(n/a)	(n/a)	SQL_Latin1_General_CP1_CI_AS
EscalationReason	Description	no	510	     	     	yes	(n/a)	(n/a)	SQL_Latin1_General_CP1_CI_AS
SupervisionFlag	varchar	no	2	     	     	yes	no	yes	SQL_Latin1_General_CP1_CI_AS
SupervisedByOne	OperatorID	no	50	     	     	yes	(n/a)	(n/a)	SQL_Latin1_General_CP1_CI_AS
SupervisedOnOne	datetime	no	8	     	     	yes	(n/a)	(n/a)	NULL
SupervisedByTwo	OperatorID	no	50	     	     	yes	(n/a)	(n/a)	SQL_Latin1_General_CP1_CI_AS
SupervisedOnTwo	datetime	no	8	     	     	yes	(n/a)	(n/a)	NULL
AuthorizedBy	OperatorID	no	50	     	     	yes	(n/a)	(n/a)	SQL_Latin1_General_CP1_CI_AS
AuthorizedOn	datetime	no	8	     	     	yes	(n/a)	(n/a)	NULL
Escalalated	bit	no	1	     	     	yes	(n/a)	(n/a)	NULL
ImportBatchID	varchar	no	20	     	     	yes	no	yes	SQL_Latin1_General_CP1_CI_AS
ClearedBy	varchar	no	25	     	     	yes	no	yes	SQL_Latin1_General_CP1_CI_AS
ClearedOn	datetime	no	8	     	     	yes	(n/a)	(n/a)	NULL
ClearedDate	datetime	no	8	     	     	yes	(n/a)	(n/a)	NULL
TrxBatchID	varchar	no	25	     	     	yes	no	yes	SQL_Latin1_General_CP1_CI_AS
Createdon	smalldatetime	no	4	     	     	yes	(n/a)	(n/a)	NULL
IsProcessed	bit	no	1	     	     	yes	(n/a)	(n/a)	NULL
ReturnedTempID	varchar	no	5	     	     	yes	no	yes	SQL_Latin1_General_CP1_CI_AS
VerifiedBy	varchar	no	35	     	     	yes	no	yes	SQL_Latin1_General_CP1_CI_AS
Verified	bit	no	1	     	     	yes	(n/a)	(n/a)	NULL
VerifiedOn	smalldatetime	no	4	     	     	yes	(n/a)	(n/a)	NULL
TrxID	varchar	no	100	     	     	yes	no	yes	SQL_Latin1_General_CP1_CI_AS
MsgID	varchar	no	100	     	     	yes	no	yes	SQL_Latin1_General_CP1_CI_AS
lrAccAsImported	varchar	no	50	     	     	yes	no	yes	SQL_Latin1_General_CP1_CI_AS
ClrBrnAsImported	varchar	no	10	     	     	yes	no	yes	SQL_Latin1_General_CP1_CI_AS