CREATE VIEW [dbo].[v_Transaction]  
   
AS  
 SELECT TrxRowID,  
   TrxBranchID,  
   TrxBatchID,  
   SerialID,  
   OurBranchID,  
   AccountTypeID,  
   AccountID,  
   ProductID,  
   ModuleID,  
   TrxCodeID,  
   TrxTypeID,  
   TrxDate,  
   ValueDate,  
   Amount,  
   LocalAmount,  
   TrxCurrencyID,  
   TrxAmount,  
   ExchangeRate,  
   MeanRate,  
   Profit,  
   ChequeID,  
   ChequeDate,  
   ReferenceNo,  
   Remarks,  
   TrxDescriptionID,  
   TrxDescription,  
   MainGLID,  
   ContraGLID,  
   '' AS TrxFlagID,  
   TrxPrinted,  
   CreatedBy,  
   CreatedOn,  
   NULL AS DeletedOn,  
   SupervisedBy,  
   SupervisedOn,  
   ImageID,  
   BREFTTrxID  
 FROM t_AccountTrx(NOLOCK)  
 UNION ALL  
 SELECT TrxRowID,  
   TrxBranchID,  
   TrxBatchID,  
   SerialID,  
   OurBranchID,  
   AccountTypeID,  
   AccountID,  
   ProductID,  
   ModuleID,  
   TrxCodeID,  
   TrxTypeID,  
   TrxDate,  
   ValueDate,  
   Amount,  
   LocalAmount,  
   TrxCurrencyID,  
   TrxAmount,  
   ExchangeRate,  
   MeanRate,  
   Profit,  
   ChequeID,  
   ChequeDate,  
   ReferenceNo,  
   Remarks,  
   TrxDescriptionID,  
   TrxDescription,  
   MainGLID,  
   ContraGLID,  
   TrxFlagID,  
   TrxPrinted,  
   CreatedBy,  
   CreatedOn,  
   DeletedOn,  
   SupervisedBy,  
   SupervisedOn,  
   ImageID,  
   BREFTTrxID  
FROM  t_Transaction(NOLOCK)  
  
  
  
  
  
  